//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.28 at 09:32:15 AM CEST 
//


package org.example.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for categoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="categoryType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Elektronika"/&gt;
 *     &lt;enumeration value="Bútor"/&gt;
 *     &lt;enumeration value="Könyvek"/&gt;
 *     &lt;enumeration value="Konyha"/&gt;
 *     &lt;enumeration value="Ruházat"/&gt;
 *     &lt;enumeration value="Sport"/&gt;
 *     &lt;enumeration value="Játék"/&gt;
 *     &lt;enumeration value="Egészség"/&gt;
 *     &lt;enumeration value="Kert"/&gt;
 *     &lt;enumeration value="Autó"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "categoryType")
@XmlEnum
public enum CategoryType {

    @XmlEnumValue("Elektronika")
    ELEKTRONIKA("Elektronika"),
    @XmlEnumValue("B\u00fator")
    BÚTOR("B\u00fator"),
    @XmlEnumValue("K\u00f6nyvek")
    KÖNYVEK("K\u00f6nyvek"),
    @XmlEnumValue("Konyha")
    KONYHA("Konyha"),
    @XmlEnumValue("Ruh\u00e1zat")
    RUHÁZAT("Ruh\u00e1zat"),
    @XmlEnumValue("Sport")
    SPORT("Sport"),
    @XmlEnumValue("J\u00e1t\u00e9k")
    JÁTÉK("J\u00e1t\u00e9k"),
    @XmlEnumValue("Eg\u00e9szs\u00e9g")
    EGÉSZSÉG("Eg\u00e9szs\u00e9g"),
    @XmlEnumValue("Kert")
    KERT("Kert"),
    @XmlEnumValue("Aut\u00f3")
    AUTÓ("Aut\u00f3");
    private final String value;

    CategoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CategoryType fromValue(String v) {
        for (CategoryType c: CategoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
